### ISSUE TITLE
Questions about Normal reward processes

### ISSUE THREAD

**Issue by yayayaoyaoyao** [jedwards24/gittins#6]
Hi, I am wondering if this package can handle the sitution mentioned in Gittins et.al 2011 8.3 mean and variance both unknown?
I have read the instruction of this package, it looks like it can handle section 8.2 with known variance, how about section 8.3?

Thanks.

**Comment by jedwards24** [comment]
Hi @yayayaoyaoyao. I had a look at the book and Table 8.3 gives ratios of unknown indices to known indices so this could be used to convert values from this package for some values. It should also be possible calculate unknown indices in a similar way to this package by substituting t-distributions for normal distributions, but this will require a larger grid and so will be harder to get indices with the same accuracy especially for smaller n.
